// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kin.proto

package kinpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Handshake
	//	*Envelope_HandshakeAck
	//	*Envelope_FileRequest
	//	*Envelope_FileResponse
	//	*Envelope_FileChunk
	//	*Envelope_RelayRegister
	//	*Envelope_RelayRegistered
	//	*Envelope_RelayConnect
	//	*Envelope_RelayRendezvous
	//	*Envelope_RelayError
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_kin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeAck() *HandshakeAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *Envelope) GetFileRequest() *FileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileRequest); ok {
			return x.FileRequest
		}
	}
	return nil
}

func (x *Envelope) GetFileResponse() *FileResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileResponse); ok {
			return x.FileResponse
		}
	}
	return nil
}

func (x *Envelope) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *Envelope) GetRelayRegister() *RelayRegister {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayRegister); ok {
			return x.RelayRegister
		}
	}
	return nil
}

func (x *Envelope) GetRelayRegistered() *RelayRegistered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayRegistered); ok {
			return x.RelayRegistered
		}
	}
	return nil
}

func (x *Envelope) GetRelayConnect() *RelayConnect {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayConnect); ok {
			return x.RelayConnect
		}
	}
	return nil
}

func (x *Envelope) GetRelayRendezvous() *RelayRendezvous {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayRendezvous); ok {
			return x.RelayRendezvous
		}
	}
	return nil
}

func (x *Envelope) GetRelayError() *RelayError {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayError); ok {
			return x.RelayError
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type Envelope_HandshakeAck struct {
	HandshakeAck *HandshakeAck `protobuf:"bytes,2,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"`
}

type Envelope_FileRequest struct {
	FileRequest *FileRequest `protobuf:"bytes,3,opt,name=file_request,json=fileRequest,proto3,oneof"`
}

type Envelope_FileResponse struct {
	FileResponse *FileResponse `protobuf:"bytes,4,opt,name=file_response,json=fileResponse,proto3,oneof"`
}

type Envelope_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,5,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type Envelope_RelayRegister struct {
	// Relay signaling messages (6–10)
	RelayRegister *RelayRegister `protobuf:"bytes,6,opt,name=relay_register,json=relayRegister,proto3,oneof"`
}

type Envelope_RelayRegistered struct {
	RelayRegistered *RelayRegistered `protobuf:"bytes,7,opt,name=relay_registered,json=relayRegistered,proto3,oneof"`
}

type Envelope_RelayConnect struct {
	RelayConnect *RelayConnect `protobuf:"bytes,8,opt,name=relay_connect,json=relayConnect,proto3,oneof"`
}

type Envelope_RelayRendezvous struct {
	RelayRendezvous *RelayRendezvous `protobuf:"bytes,9,opt,name=relay_rendezvous,json=relayRendezvous,proto3,oneof"`
}

type Envelope_RelayError struct {
	RelayError *RelayError `protobuf:"bytes,10,opt,name=relay_error,json=relayError,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

func (*Envelope_Handshake) isEnvelope_Payload() {}

func (*Envelope_HandshakeAck) isEnvelope_Payload() {}

func (*Envelope_FileRequest) isEnvelope_Payload() {}

func (*Envelope_FileResponse) isEnvelope_Payload() {}

func (*Envelope_FileChunk) isEnvelope_Payload() {}

func (*Envelope_RelayRegister) isEnvelope_Payload() {}

func (*Envelope_RelayRegistered) isEnvelope_Payload() {}

func (*Envelope_RelayConnect) isEnvelope_Payload() {}

func (*Envelope_RelayRendezvous) isEnvelope_Payload() {}

func (*Envelope_RelayError) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`          // 32-byte SHA-256(pubkey)
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32-byte Ed25519 pubkey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_kin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Handshake) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type HandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_kin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeAck) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *HandshakeAck) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // 32-byte SHA-256 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_kin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{3}
}

func (x *FileRequest) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	NotFound      bool                   `protobuf:"varint,3,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_kin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{4}
}

func (x *FileResponse) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *FileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_kin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{5}
}

func (x *FileChunk) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_kin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Node → Relay: register this node.
type RelayRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        []byte                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`              // 32 bytes
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`     // 32 bytes Ed25519
	ListenPort    uint32                 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"` // internal TCP port the node listens on for kin connections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRegister) Reset() {
	*x = RelayRegister{}
	mi := &file_kin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRegister) ProtoMessage() {}

func (x *RelayRegister) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRegister.ProtoReflect.Descriptor instead.
func (*RelayRegister) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{7}
}

func (x *RelayRegister) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *RelayRegister) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RelayRegister) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

// Relay → Node: registration confirmed.
type RelayRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalAddr  string                 `protobuf:"bytes,1,opt,name=external_addr,json=externalAddr,proto3" json:"external_addr,omitempty"` // "ip:port" as seen by relay's TCP listener
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRegistered) Reset() {
	*x = RelayRegistered{}
	mi := &file_kin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRegistered) ProtoMessage() {}

func (x *RelayRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRegistered.ProtoReflect.Descriptor instead.
func (*RelayRegistered) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{8}
}

func (x *RelayRegistered) GetExternalAddr() string {
	if x != nil {
		return x.ExternalAddr
	}
	return ""
}

// Node B → Relay: request rendezvous with target node.
type RelayConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  []byte                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayConnect) Reset() {
	*x = RelayConnect{}
	mi := &file_kin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConnect) ProtoMessage() {}

func (x *RelayConnect) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConnect.ProtoReflect.Descriptor instead.
func (*RelayConnect) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{9}
}

func (x *RelayConnect) GetTargetNodeId() []byte {
	if x != nil {
		return x.TargetNodeId
	}
	return nil
}

// Relay → both A and B: peer info for simultaneous TCP connect.
type RelayRendezvous struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerNodeId       []byte                 `protobuf:"bytes,1,opt,name=peer_node_id,json=peerNodeId,proto3" json:"peer_node_id,omitempty"`                   // 32 bytes
	PeerPublicKey    []byte                 `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`          // 32 bytes — for TLS verification after punch
	PeerExternalAddr string                 `protobuf:"bytes,3,opt,name=peer_external_addr,json=peerExternalAddr,proto3" json:"peer_external_addr,omitempty"` // "ip:listen_port" — punch target
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelayRendezvous) Reset() {
	*x = RelayRendezvous{}
	mi := &file_kin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRendezvous) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRendezvous) ProtoMessage() {}

func (x *RelayRendezvous) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRendezvous.ProtoReflect.Descriptor instead.
func (*RelayRendezvous) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{10}
}

func (x *RelayRendezvous) GetPeerNodeId() []byte {
	if x != nil {
		return x.PeerNodeId
	}
	return nil
}

func (x *RelayRendezvous) GetPeerPublicKey() []byte {
	if x != nil {
		return x.PeerPublicKey
	}
	return nil
}

func (x *RelayRendezvous) GetPeerExternalAddr() string {
	if x != nil {
		return x.PeerExternalAddr
	}
	return ""
}

// Relay → Node: rendezvous failed.
type RelayError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "peer_not_registered", "peer_not_found"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayError) Reset() {
	*x = RelayError{}
	mi := &file_kin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayError) ProtoMessage() {}

func (x *RelayError) ProtoReflect() protoreflect.Message {
	mi := &file_kin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayError.ProtoReflect.Descriptor instead.
func (*RelayError) Descriptor() ([]byte, []int) {
	return file_kin_proto_rawDescGZIP(), []int{11}
}

func (x *RelayError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kin_proto protoreflect.FileDescriptor

const file_kin_proto_rawDesc = "" +
	"\n" +
	"\tkin.proto\x12\x03kin\"\xf6\x04\n" +
	"\bEnvelope\x12.\n" +
	"\thandshake\x18\x01 \x01(\v2\x0e.kin.HandshakeH\x00R\thandshake\x128\n" +
	"\rhandshake_ack\x18\x02 \x01(\v2\x11.kin.HandshakeAckH\x00R\fhandshakeAck\x125\n" +
	"\ffile_request\x18\x03 \x01(\v2\x10.kin.FileRequestH\x00R\vfileRequest\x128\n" +
	"\rfile_response\x18\x04 \x01(\v2\x11.kin.FileResponseH\x00R\ffileResponse\x12/\n" +
	"\n" +
	"file_chunk\x18\x05 \x01(\v2\x0e.kin.FileChunkH\x00R\tfileChunk\x12;\n" +
	"\x0erelay_register\x18\x06 \x01(\v2\x12.kin.RelayRegisterH\x00R\rrelayRegister\x12A\n" +
	"\x10relay_registered\x18\a \x01(\v2\x14.kin.RelayRegisteredH\x00R\x0frelayRegistered\x128\n" +
	"\rrelay_connect\x18\b \x01(\v2\x11.kin.RelayConnectH\x00R\frelayConnect\x12A\n" +
	"\x10relay_rendezvous\x18\t \x01(\v2\x14.kin.RelayRendezvousH\x00R\x0frelayRendezvous\x122\n" +
	"\vrelay_error\x18\n" +
	" \x01(\v2\x0f.kin.RelayErrorH\x00R\n" +
	"relayError\x12\"\n" +
	"\x05error\x18\x0f \x01(\v2\n" +
	".kin.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"C\n" +
	"\tHandshake\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"F\n" +
	"\fHandshakeAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"&\n" +
	"\vFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\"X\n" +
	"\fFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tnot_found\x18\x03 \x01(\bR\bnotFound\"J\n" +
	"\tFileChunk\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\rRelayRegister\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\rR\n" +
	"listenPort\"6\n" +
	"\x0fRelayRegistered\x12#\n" +
	"\rexternal_addr\x18\x01 \x01(\tR\fexternalAddr\"4\n" +
	"\fRelayConnect\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\fR\ftargetNodeId\"\x89\x01\n" +
	"\x0fRelayRendezvous\x12 \n" +
	"\fpeer_node_id\x18\x01 \x01(\fR\n" +
	"peerNodeId\x12&\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\fR\rpeerPublicKey\x12,\n" +
	"\x12peer_external_addr\x18\x03 \x01(\tR\x10peerExternalAddr\"$\n" +
	"\n" +
	"RelayError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB\x1dZ\x1bgithub.com/niklod/kin/kinpbb\x06proto3"

var (
	file_kin_proto_rawDescOnce sync.Once
	file_kin_proto_rawDescData []byte
)

func file_kin_proto_rawDescGZIP() []byte {
	file_kin_proto_rawDescOnce.Do(func() {
		file_kin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kin_proto_rawDesc), len(file_kin_proto_rawDesc)))
	})
	return file_kin_proto_rawDescData
}

var file_kin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kin_proto_goTypes = []any{
	(*Envelope)(nil),        // 0: kin.Envelope
	(*Handshake)(nil),       // 1: kin.Handshake
	(*HandshakeAck)(nil),    // 2: kin.HandshakeAck
	(*FileRequest)(nil),     // 3: kin.FileRequest
	(*FileResponse)(nil),    // 4: kin.FileResponse
	(*FileChunk)(nil),       // 5: kin.FileChunk
	(*Error)(nil),           // 6: kin.Error
	(*RelayRegister)(nil),   // 7: kin.RelayRegister
	(*RelayRegistered)(nil), // 8: kin.RelayRegistered
	(*RelayConnect)(nil),    // 9: kin.RelayConnect
	(*RelayRendezvous)(nil), // 10: kin.RelayRendezvous
	(*RelayError)(nil),      // 11: kin.RelayError
}
var file_kin_proto_depIdxs = []int32{
	1,  // 0: kin.Envelope.handshake:type_name -> kin.Handshake
	2,  // 1: kin.Envelope.handshake_ack:type_name -> kin.HandshakeAck
	3,  // 2: kin.Envelope.file_request:type_name -> kin.FileRequest
	4,  // 3: kin.Envelope.file_response:type_name -> kin.FileResponse
	5,  // 4: kin.Envelope.file_chunk:type_name -> kin.FileChunk
	7,  // 5: kin.Envelope.relay_register:type_name -> kin.RelayRegister
	8,  // 6: kin.Envelope.relay_registered:type_name -> kin.RelayRegistered
	9,  // 7: kin.Envelope.relay_connect:type_name -> kin.RelayConnect
	10, // 8: kin.Envelope.relay_rendezvous:type_name -> kin.RelayRendezvous
	11, // 9: kin.Envelope.relay_error:type_name -> kin.RelayError
	6,  // 10: kin.Envelope.error:type_name -> kin.Error
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kin_proto_init() }
func file_kin_proto_init() {
	if File_kin_proto != nil {
		return
	}
	file_kin_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Handshake)(nil),
		(*Envelope_HandshakeAck)(nil),
		(*Envelope_FileRequest)(nil),
		(*Envelope_FileResponse)(nil),
		(*Envelope_FileChunk)(nil),
		(*Envelope_RelayRegister)(nil),
		(*Envelope_RelayRegistered)(nil),
		(*Envelope_RelayConnect)(nil),
		(*Envelope_RelayRendezvous)(nil),
		(*Envelope_RelayError)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kin_proto_rawDesc), len(file_kin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kin_proto_goTypes,
		DependencyIndexes: file_kin_proto_depIdxs,
		MessageInfos:      file_kin_proto_msgTypes,
	}.Build()
	File_kin_proto = out.File
	file_kin_proto_goTypes = nil
	file_kin_proto_depIdxs = nil
}
